FROM golang:1.12-alpine as builder

ENV GO111MODULE=on

RUN mkdir -p /app

WORKDIR /app
COPY . .

RUN apk --no-cache add git alpine-sdk build-base gcc

RUN go build -o main

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app .

CMD ["./main"]
