version: '3'

services:

#Postgre
  db:
    image: postgres:alpine
    volumes:
       - ./info.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      replicas: 1
#    networks:
#       - overlay
  
#Node
  go:
    image: tuannx/golang-crud
    depends_on:
      - db
    ports:
        - "8081:8080"

#networks:
#  overlay: